version: '3.3'

networks:

  lb-goat-network:
    driver: bridge
    
  lb-farmer-network:
    driver: bridge

services:
  
  lb-goat:
    image: ${LB_IMAGE_TAG}
    command: '-config=/var/haproxy/tmp/haproxy.hcl -consul-addr=${CONSUL_ADDR}'
    ports:
      - target: 8202
        published: ${GOAT_HAPROXY_APP_PORT}
        mode: host
      - target: 8404
        published: ${GOAT_HAPROXY_STATS_PORT}
        mode: host
    environment:
      - APP_NAME=${GOAT_APP_NAME}
    labels:
      com.bbarrett.loadbalancer.service: ${GOAT_APP_NAME}
    networks:
      - lb-${GOAT_APP_NAME}-network

  registrator-goat:
    image: ${REGISTRATOR_IMAGE_TAG}
    command: > 
      -health-addr=lb-goat:8404
      -health-url-path=/health
      -consul-addr=${CONSUL_ADDR}
      -registration-name=lb-${GOAT_APP_NAME}
      -registration-addr=${HOST_IP}:${GOAT_HAPROXY_APP_PORT}
      -registration-ttl=${REGISTRATION_TTL}
    labels:
      com.bbarrett.registrator.name: lb-${GOAT_APP_NAME}
      com.bbarrett.registrator.address: ${HOST_IP}:${GOAT_HAPROXY_APP_PORT}
    networks:
      - lb-${GOAT_APP_NAME}-network

  lb-farmer:
    image: ${LB_IMAGE_TAG}
    command: '-config=/var/haproxy/tmp/haproxy.hcl -consul-addr=${CONSUL_ADDR}'
    ports:
      - target: 8202
        published: ${FARMER_HAPROXY_APP_PORT}
        mode: host
      - target: 8404
        published: ${FARMER_HAPROXY_STATS_PORT}
        mode: host
    environment:
      - APP_NAME=${FARMER_APP_NAME}
    labels:
      com.bbarrett.loadbalancer.service: ${FARMER_APP_NAME}
    networks:
      - lb-${FARMER_APP_NAME}-network

  registrator-farmer:
    image: ${REGISTRATOR_IMAGE_TAG}
    command: > 
      -health-addr=lb-farmer:8404
      -health-url-path=/health
      -consul-addr=${CONSUL_ADDR}
      -registration-name=lb-${FARMER_APP_NAME}
      -registration-addr=${HOST_IP}:${FARMER_HAPROXY_APP_PORT}
      -registration-ttl=${REGISTRATION_TTL}
    labels:
      com.bbarrett.registrator.name: lb-${FARMER_APP_NAME}
      com.bbarrett.registrator.address: ${HOST_IP}:${FARMER_HAPROXY_APP_PORT}
    networks:
      - lb-${FARMER_APP_NAME}-network

  gonsul:
    image: ${GONSUL_IMAGE_TAG}
    command: >
      --consul-url=http://${CONSUL_ADDR}
      --strategy=POLL
      --poll-interval=5
      --log-level=INFO
      --repo-url=${CONFIG_REPO_URL}
      --repo-branch=${CONFIG_REPO_BRANCH}
      --repo-base-path=${CONFIG_REPO_BASE_PATH}
      --repo-ssh-key=/home/gonsul/.ssh/id_rsa
      --repo-ssh-user=git
      --repo-root=/home/gonsul/tmp
      --expand-json=true
      --allow-deletes=true
    ports:
      - target: 8000
        published: ${GONSUL_PORT}
        mode: host
    labels:
      com.bbarrett.gonsul.consul: ${CONSUL_ADDR}
      com.bbarrett.gonsul.repo.url: ${CONFIG_REPO_URL}
      com.bbarrett.gonsul.repo.branch: ${CONFIG_REPO_BRANCH}
      com.bbarrett.gonsul.repo.basepath: ${CONFIG_REPO_BASE_PATH}
    volumes:
      - type: bind
        source: ~/.ssh
        target: /tmp/.ssh
        read_only: true

  consul:
    image: consul:latest
    command: 'agent -server -bootstrap -ui -client=0.0.0.0'
    ports:
      - target: 8400
        published: 8400
        mode: host
      - target: 8500
        published: 8500
        mode: host
      - target: 8600
        published: 8600
        protocol: udp
        mode: host
